---
deployment:
  tasks:
    - export REPO="/home/painclin/repositories/Pain-Clinic"
    - export SRC_THEME="$REPO/app/public/wp-content/themes/pain-clinic-theme"
    - export SRC_PLUGINS="$REPO/app/public/wp-content/plugins"
    - export DOCROOT="/home/painclin/public_html/pain"
    - export DEST_THEME="$DOCROOT/wp-content/themes/pain-clinic-theme"
    - export DEST_PLUGINS="$DOCROOT/wp-content/plugins"

    - /bin/mkdir -p "$DEST_THEME"
    - /bin/mkdir -p "$DEST_PLUGINS"

    - /bin/ls -la "$SRC_THEME"
    - /bin/ls -la "$SRC_PLUGINS" || true

    # Copy theme (clean)
    - /bin/rm -rf "$DEST_THEME"
    - /bin/mkdir -p "$DEST_THEME"
    - /bin/cp -a "$SRC_THEME/." "$DEST_THEME/"

    # Copy each plugin (loop via find, avoids inline 'then')
    - /usr/bin/find "$SRC_PLUGINS" -mindepth 1 -maxdepth 1 -type d -exec sh -c '
        for dir; do
          name=$(basename "$dir")
          echo "Deploying plugin $name"
          rm -rf "$DEST_PLUGINS/$name"
          cp -a "$dir" "$DEST_PLUGINS/"
        done
      ' sh {} +

    - /bin/date > "$DEST_THEME/DEPLOY_OK.txt"
