---
deployment:
  tasks:
    # Absolute repo & sources (copy EXACTLY the path shown in cPanel > Git)
    - export REPO=/home/painclin/repositories/Pain-Clinic
    - export SRC_THEME=$REPO/app/public/wp-content/themes/pain-clinic-theme
    - export SRC_PLUGINS=$REPO/app/public/wp-content/plugins

    # Live WordPress paths (pain-clinic.ir)
    - export DOCROOT=/home/painclin/public_html/pain
    - export DEST_THEME=$DOCROOT/wp-content/themes/pain-clinic-theme
    - export DEST_PLUGINS=$DOCROOT/wp-content/plugins

    # Ensure targets
    - /bin/mkdir -p $DEST_THEME
    - /bin/mkdir -p $DEST_PLUGINS

    # Diagnostics
    - echo "== ls SRC_THEME ==" && /bin/ls -la "$SRC_THEME" || true
    - echo "== ls SRC_PLUGINS ==" && /bin/ls -la "$SRC_PLUGINS" || true

    # Copy THEME
    - >
      if [ -d "$SRC_THEME" ]; then
        echo "SYNC THEME from $SRC_THEME => $DEST_THEME";
        /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" "$SRC_THEME/" "$DEST_THEME/";
      else
        echo "ERROR: theme source not found at $SRC_THEME"; exit 1;
      fi

    # Copy PLUGINS (optional)
    - >
      if [ -d "$SRC_PLUGINS" ]; then
        echo "SYNC PLUGINS from $SRC_PLUGINS => $DEST_PLUGINS";
        /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" "$SRC_PLUGINS/" "$DEST_PLUGINS/";
      else
        echo "No plugins folder at $SRC_PLUGINS (skipping)";
      fi

    # Mark success visibly
    - /bin/date > "$DEST_THEME/DEPLOY_OK.txt"
