---
deployment:
  tasks:
    - export REPO="/home/painclin/repositories/Pain-Clinic"
    - export SRC_THEME="$REPO/app/public/wp-content/themes/pain-clinic-theme"
    - export SRC_PLUGINS="$REPO/app/public/wp-content/plugins"
    - export DOCROOT="/home/painclin/public_html/pain"
    - export DEST_THEME="$DOCROOT/wp-content/themes/pain-clinic-theme"
    - export DEST_PLUGINS="$DOCROOT/wp-content/plugins"

    # Ensure targets
    - /bin/mkdir -p "$DEST_THEME"
    - /bin/mkdir -p "$DEST_PLUGINS"

    # Diagnostics (optional)
    - /bin/ls -la "$SRC_THEME"
    - /bin/ls -la "$SRC_PLUGINS" || true

    # THEME (clean copy)
    - /bin/rm -rf "$DEST_THEME"
    - /bin/mkdir -p "$DEST_THEME"
    - /bin/cp -a "$SRC_THEME/." "$DEST_THEME/"

    # PLUGINS (simple copy, overwrite if exists; no delete)
    - /bin/cp -a "$SRC_PLUGINS/." "$DEST_PLUGINS/"

    # Marker so you can see a successful deploy
    - /bin/date > "$DEST_THEME/DEPLOY_OK.txt"
