---
deployment:
  tasks:
    - export DOCROOT=/home/painclin/public_html/pain
    - export THEME_SLUG=pain-clinic-theme
    - export DEST_THEME=$DOCROOT/wp-content/themes/$THEME_SLUG
    - export DEST_PLUGINS=$DOCROOT/wp-content/plugins

    # Ensure targets
    - /bin/mkdir -p $DEST_THEME
    - /bin/mkdir -p $DEST_PLUGINS

    # Diagnostics (shows what cPanel actually sees)
    - echo "== repo pwd ==" && /bin/pwd
    - echo "== dirs depth 3 ==" && /usr/bin/find . -maxdepth 3 -type d -print

    # Try both possible source roots
    - export SRC_A=./wp-content/themes/$THEME_SLUG
    - export SRC_B=./app/public/wp-content/themes/$THEME_SLUG

    # Show what exists
    - /bin/ls -la "$SRC_A" || true
    - /bin/ls -la "$SRC_B" || true

    # Copy from the first existing source (now with --delete for clean deploys)
    - >
      if [ -d "$SRC_A" ]; then
        echo "SYNC from $SRC_A";
        /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" "$SRC_A/" "$DEST_THEME/";
      elif [ -d "$SRC_B" ]; then
        echo "SYNC from $SRC_B";
        /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" "$SRC_B/" "$DEST_THEME/";
      else
        echo "ERROR: theme source path not found (checked $SRC_A and $SRC_B)";
        exit 1;
      fi

    # Plugins (if you have any)
    - >
      if [ -d "./wp-content/plugins" ]; then
        echo "Plugins from ./wp-content/plugins";
        /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" "./wp-content/plugins/" "$DEST_PLUGINS/";
      elif [ -d "./app/public/wp-content/plugins" ]; then
        echo "Plugins from ./app/public/wp-content/plugins";
        /bin/rsync -av --delete --exclude=".git*" --exclude=".cpanel.yml" "./app/public/wp-content/plugins/" "$DEST_PLUGINS/";
      else
        echo "No plugins folder found in repo";
      fi
